name: Backend CI/CD

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist/
      - name: Deploy to server
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.2.0
        env:
          PORT: ${{ secrets.BACKEND_PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REPO_URL: https://github.com/jlozoya/notes-app.git
          BRANCH: master
          APP_NAME: notesapp
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: PORT,MONGO_URI,JWT_SECRET,REPO_URL,BRANCH,APP_NAME
          script: |
            set -euo pipefail

            # Choose a base directory under the SSH user’s HOME
            APP_ROOT="$HOME/notesapp"
            BACKEND_DIR="$APP_ROOT/backend"

            # Ensure git & node available (optional: adjust to your stack)
            if ! command -v git >/dev/null; then
              sudo apt-get update -y && sudo apt-get install -y git
            fi
            if ! command -v node >/dev/null; then
              # Install Node.js 20 (Nodesource)
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null; then
              sudo npm i -g pm2
            fi

            # Create app root if missing
            mkdir -p "$APP_ROOT"

            # Clone repo if the directory (or .git) is missing; otherwise update
            if [ ! -d "$APP_ROOT/.git" ]; then
              echo "Cloning repo into $APP_ROOT ..."
              git clone --branch "$BRANCH" "$REPO_URL" "$APP_ROOT"
            else
              echo "Updating repo in $APP_ROOT ..."
              cd "$APP_ROOT"
              git fetch origin "$BRANCH"
              git checkout "$BRANCH"
              git pull --ff-only origin "$BRANCH"
            fi

            # Enter backend folder
            cd "$BACKEND_DIR"

            # Write .env from GitHub secrets
            umask 0077
            cat > .env <<'EOF'
            PORT=${PORT}
            MONGO_URI=${MONGO_URI}
            JWT_SECRET=${JWT_SECRET}
            EOF

            # Install prod deps & build
            npm ci --omit=dev
            npm run build

            # Start / restart with PM2
            if pm2 describe "$APP_NAME" >/dev/null 2>&1; then
              pm2 restart "$APP_NAME"
            else
              pm2 start dist/index.js --name "$APP_NAME"
            fi
            pm2 save

            echo "Deploy complete at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
