name: Backend CI/CD 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Node setup ---
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # --- Install dependencies ---
      - name: Install dependencies
        run: npm ci

      # --- Type check & build ---
      - name: Build TypeScript
        run: npm run build

      # --- Optional tests ---
      - name: Run tests
        run: npm test
        continue-on-error: true   # remove if you want to block on tests

      # --- Archive build artifacts (for debug/download) ---
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      # --- Deploy (example: Lightsail via SSH) ---
      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/notesapp/backend
            git pull origin main
            npm ci
            npm run build
            pm2 restart notesapp || pm2 start dist/index.js --name notesapp