name: Frontend CI/CD

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci-cd.yml'
  pull_request:
    branches: [master]
    paths:
      - 'frontend/**'

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-web:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        continue-on-error: true
      - name: Build web
        env:
          EXPO_PUBLIC_API_URL: https://notesapp.lozoya.org
        run: npx expo export -p web
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      - name: Upload web build to Lightsail
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./dist/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:notesapp/frontend/
  build-mobile:
    needs: deploy-web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EAS_ANDROID_READY: ${{ secrets.EAS_ANDROID_READY }}
      EXPO_PUBLIC_API_URL: https://notesapp.lozoya.org
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install EAS/Expo CLI
        run: |
          npm i -g eas-cli
          npm i -g expo-cli || true
      #- name: Build iOS (EAS)
      #  run: eas build --platform ios --non-interactive --profile production
      - name: Build Android (EAS)
        if: env.EAS_ANDROID_READY == '1'
        run: eas build --platform android --non-interactive --profile production
      - name: Skip Android (keystore not configured)
        if: env.EAS_ANDROID_READY != '1'
        run: echo "Skipping Android build. Set repo secret EAS_ANDROID_READY=1 AFTER running 'eas credentials -p android' to generate/upload a keystore."
