name: Frontend CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Set up Node environment ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # --- Install dependencies ---
      - name: Install dependencies
        run: npm ci

      # --- Run type checks & tests ---
      - name: Run tests
        run: npm test

      # --- Expo/EAS login ---
      - name: Log in to Expo
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      # --- Build app with EAS ---
      - name: Build (EAS)
        run: npx eas build --platform all --non-interactive --profile production

      # --- (Optional) Publish OTA update ---
      - name: Publish OTA update
        if: github.ref == 'refs/heads/main'
        run: npx expo publish --non-interactive
